spring.application.name=feedback-ms
server.port=8090

spring.datasource.url=jdbc:h2:mem:feedbackdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.properties.hibernate.format_sql=true
feedback.moderation.blocked-words=insulte,haine,raciste,violence,arnaque,spam,escroc
feedback.moderation.auto-block-threshold=70
feedback.auto-reclamation.enabled=true
feedback.auto-reclamation.negative-threshold=2
