spring.application.name=inscription-ms
server.port=8081

spring.datasource.url=jdbc:h2:mem:inscriptiondb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.properties.hibernate.format_sql=true
