spring.application.name=reclamation-ms
server.port=8091

spring.datasource.url=jdbc:h2:mem:reclamationdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.properties.hibernate.format_sql=true
reclamation.classification.high-keywords=retard intervention,urgence,danger,accident,panne totale,service indisponible,impossible d utiliser,bloque
reclamation.classification.medium-keywords=bug,erreur,deconnexion,paiement,lent,instable,retard,interruption
reclamation.classification.low-keywords=gps ne marche pas,gps,suggestion,affichage
reclamation.classification.high-threshold=70
reclamation.classification.medium-threshold=35
