spring.application.name=reclamation-ms
server.port=8091

spring.datasource.url=jdbc:h2:mem:reclamationdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.properties.hibernate.format_sql=true
